### ISSUE TITLE
MaterialLink enable property look and feel is the same

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#475]
When I try to use MaterialLink component and need to disable under some situation, there is no look and feel difference between enabled and disabled. I thought it should be text/icon color turning to grey and cursor turning to pointer, so user can realize it's disabled at the first time. May have enhancement for it?
gwt-material version: 1.6.2
sample code: MaterialLink link = new MaterialLink();
                      link.setEnabled (false);

**Comment by kevzlou7979** [comment]
Thanks for the catch will update it on 2.0

**Comment by peggieHou** [comment]
MaterialIcon and MaterialCard have the same issue. Could enhance for them too? Thanks!

**Comment by kevzlou7979** [comment]
Here is a workaround about this issue.
we will a patch on GMD 2.0 as this is a minor and cosmetic update.
```css
button.disabled, i.disabled, a.disabled {
    background-color: #DFDFDF !important;
    box-shadow: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    color: #9F9F9F !important;
    cursor: default !important;
    transition: none !important;
}

i.disabled, a.disabled  {
    background-color: #fff !important;
}
```
