### ISSUE TITLE
Feature request: MaterialChip border radius configurable

### ISSUE THREAD

**Issue by adibacco** [GwtMaterialDesign/gwt-material#537]
There is no way to configure the MaterialChip border radius. 
This is not  a bug but a feature request.

**Comment by kevzlou7979** [comment]
You can easily set the border radius of the chip by doing this on your custom css:
```css
    .chip {
           border-radius: 0px;
    }
```
